name: fp_pemrograman
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Updated SDK constraint for compatibility

dependencies:
  flutter:
    sdk: flutter

  # Firebase Essentials
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  firebase_storage: ^11.7.0

  # UI & Functionality
  google_fonts: ^6.1.0
  image_picker: ^1.1.2 # Version updated and duplicate removed
  geolocator: ^10.1.0
  http: ^1.2.0
  permission_handler: ^11.3.1
  flutter_spinkit: ^5.2.0
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  path: ^1.9.0
  url_launcher: ^6.2.1
  image: ^3.2.2 # <--- ADDED: For image manipulation (resizing, etc.)
  tflite_flutter: 
    git:
      url: https://github.com/zakkkkkkkkkkkk/flutter-tflite.git
      ref: main # Use the main branch of the forked repository

  # Note: google_sign_in is not used in our current flow but left here for now.
  google_sign_in: ^6.3.0

  cupertino_icons: ^1.0.8
  mapbox_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/model.tflite # <--- ADDED: Your TFLite model
    - assets/models/labels.txt   # <--- ADDED: Your labels file

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
