// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8whgfRz5zI9pTTbpqYmz5Gdzem2TcMCE',
    appId: '1:1033832187751:web:0424f65c668d39caa411c2',
    messagingSenderId: '1033832187751',
    projectId: 'dermai-b819e',
    authDomain: 'dermai-b819e.firebaseapp.com',
    storageBucket: 'dermai-b819e.firebasestorage.app',
    measurementId: 'G-H48J243YDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MlPwMx0k_OqQzmuWCVDIfM-mWoOq1cc',
    appId: '1:1033832187751:android:ea9a3facf931fe25a411c2',
    messagingSenderId: '1033832187751',
    projectId: 'dermai-b819e',
    storageBucket: 'dermai-b819e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5l4xRH_ous0z7OlpLjLvhU5D6gHeIEWU',
    appId: '1:1033832187751:ios:0525fafb3d5b72c2a411c2',
    messagingSenderId: '1033832187751',
    projectId: 'dermai-b819e',
    storageBucket: 'dermai-b819e.firebasestorage.app',
    iosBundleId: 'com.example.fpPemrograman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5l4xRH_ous0z7OlpLjLvhU5D6gHeIEWU',
    appId: '1:1033832187751:ios:0525fafb3d5b72c2a411c2',
    messagingSenderId: '1033832187751',
    projectId: 'dermai-b819e',
    storageBucket: 'dermai-b819e.firebasestorage.app',
    iosBundleId: 'com.example.fpPemrograman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8whgfRz5zI9pTTbpqYmz5Gdzem2TcMCE',
    appId: '1:1033832187751:web:04ce56de856ec870a411c2',
    messagingSenderId: '1033832187751',
    projectId: 'dermai-b819e',
    authDomain: 'dermai-b819e.firebaseapp.com',
    storageBucket: 'dermai-b819e.firebasestorage.app',
    measurementId: 'G-L268CDWLZS',
  );
}
